#!/bin/sh
#
# Lives in /.git/hooks
# 
# Called by "git commit" with the name of the file that has the
# commit message, followed by the description of the commit
# message's source.  The hook's purpose is to edit the commit
# message file.  If the hook fails with a non-zero status,
# the commit is aborted.

## Prepends part of the branch name to the commit message
# Copy the current branch's name (everything after the 1st /)
git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* .*\/\(.*\)/\1 /' > /tmp/git-commit
# Copy the original message
cat $1 >> /tmp/git-commit
# Move it back
cp /tmp/git-commit $1
